blank_issues_enabled: false
contact_links:
  - name: SustentabilidadeJ치 - Reposit칩rio Principal
    url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2_T02_G4_SustentabilidadeJ-_Entrega_01
    about: Reposit칩rio principal do projeto SustentabilidadeJ치.